server:
   port: ${PORT:9090}
message: Configuracion de trabajo en el servidor levantado!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xd?serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8088
